### ISSUE TITLE
Появилась ошибка ocStore 1.5.5.1.2, оплата проходит

### ISSUE THREAD

**Issue by zalexandr** [liqpay/plugin-opencart#3]
Появилась ошибка. Оплата проходит один раз. При этом в магазине ни слова о заказе. И вот эта ошибка.
PHP Notice: Undefined index: order_id in /catalog/controller/payment/liqpay.php on line 111
PHP Notice: Undefined index: order_id in /catalog/controller/payment/liqpay.php on line 112
Следующие заказы невозможно оплатить. "Невозможно провести оплату"

**Comment by dpzz** [comment]
Доброго времени
У нас два новых релиза, воспользуйтесь новым кодом.
